// <auto-generated />
using System;
using Health.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Health.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113041032_AddHealthPlanEntityTable")]
    partial class AddHealthPlanEntityTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Health.Domain.Entities.HealthPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_health_plans_id");

                    b.ToTable("health_plans", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.HealthPlan", b =>
                {
                    b.OwnsOne("Health.Domain.ValueObjects.AnsRegistrationCode.AnsRegistrationCode", "AnsRegistrationCode", b1 =>
                        {
                            b1.Property<Guid>("HealthPlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("text")
                                .HasColumnName("ans_registration_code");

                            b1.HasKey("HealthPlanId");

                            b1.HasIndex(new[] { "Value" }, "ix_ans_registration_code");

                            b1.ToTable("health_plans");

                            b1.WithOwner()
                                .HasForeignKey("HealthPlanId");
                        });

                    b.OwnsOne("Health.Domain.ValueObjects.Name.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("HealthPlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("HealthPlanId");

                            b1.ToTable("health_plans");

                            b1.WithOwner()
                                .HasForeignKey("HealthPlanId");
                        });

                    b.Navigation("AnsRegistrationCode")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
