// <auto-generated />
using System;
using Health.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Health.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251114211622_AddCollationInHealthPlanAndBeneficiaryTables")]
    partial class AddCollationInHealthPlanAndBeneficiaryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Health.Domain.Entities.Beneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("HealthPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_beneficiaries_id");

                    b.HasIndex("HealthPlanId");

                    b.ToTable("beneficiaries", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.HealthPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_health_plans_id");

                    b.ToTable("health_plans", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.Beneficiary", b =>
                {
                    b.HasOne("Health.Domain.Entities.HealthPlan", "HealthPlan")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("HealthPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beneficiaries_health_plans");

                    b.OwnsOne("Health.Domain.ValueObjects.Name.Name", "FullName", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("text")
                                .HasColumnName("full_name")
                                .UseCollation("case_insensitive");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.OwnsOne("Health.Domain.ValueObjects.BirthDate.BirthDate", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.OwnsOne("Health.Domain.ValueObjects.Cpf.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("text")
                                .HasColumnName("cpf");

                            b1.HasKey("BeneficiaryId");

                            b1.HasIndex(new[] { "Value" }, "ix_cpf")
                                .IsUnique();

                            b1.ToTable("beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.Navigation("BirthDate")
                        .IsRequired();

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("HealthPlan");
                });

            modelBuilder.Entity("Health.Domain.Entities.HealthPlan", b =>
                {
                    b.OwnsOne("Health.Domain.ValueObjects.Name.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("HealthPlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("text")
                                .HasColumnName("name")
                                .UseCollation("case_insensitive");

                            b1.HasKey("HealthPlanId");

                            b1.ToTable("health_plans");

                            b1.WithOwner()
                                .HasForeignKey("HealthPlanId");
                        });

                    b.OwnsOne("Health.Domain.ValueObjects.AnsRegistrationCode.AnsRegistrationCode", "AnsRegistrationCode", b1 =>
                        {
                            b1.Property<Guid>("HealthPlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("text")
                                .HasColumnName("ans_registration_code");

                            b1.HasKey("HealthPlanId");

                            b1.HasIndex(new[] { "Value" }, "ix_ans_registration_code");

                            b1.ToTable("health_plans");

                            b1.WithOwner()
                                .HasForeignKey("HealthPlanId");
                        });

                    b.Navigation("AnsRegistrationCode")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Health.Domain.Entities.HealthPlan", b =>
                {
                    b.Navigation("Beneficiaries");
                });
#pragma warning restore 612, 618
        }
    }
}
